# Generated by Django 4.1.5 on 2023-02-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_games_nfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='games',
            name='division',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='games',
            name='dmc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='games',
            name='sam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='games',
            name='spiderman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='games',
            name='tombraider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='games',
            name='uncharted',
            field=models.BooleanField(default=False),
        ),
    ]
