# Generated by Django 4.1.5 on 2023-02-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_games_ac_games_division_games_dmc_games_sam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='cod',
            field=models.BooleanField(default=False),
        ),
    ]
